In [1]:
# Testing to see that PyTorch was installed correctly.
from __future__ import print_function
import torch
x = torch.rand(5, 3)
print(x)


tensor([[0.1083, 0.7356, 0.9581],
        [0.9587, 0.8911, 0.6641],
        [0.8026, 0.3113, 0.8192],
        [0.3785, 0.9565, 0.7445],
        [0.5171, 0.4369, 0.8097]])


In [12]:
# Create two tensors of size 5x3 and 2x1 and then multiply them together.
y = torch.Tensor([5,3])
print(y)
z = torch.Tensor([2,1])
print(z)
print(z*y)

tensor([5., 3.])
tensor([2., 1.])
tensor([10.,  3.])


In [6]:
# Creates a 2x5 tensor that is initialized with zero in every index.
x = torch.zeros([2,5])
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [7]:
# Outputs the dimensions of the tensor object that the method is being called on.
x.shape

torch.Size([2, 5])

In [8]:
# Creates a tensor of size 2x5 and initializes every index with a random value.
y = torch.rand([2,5])

In [9]:
y

tensor([[0.7942, 0.4554, 0.8751, 0.8412, 0.3013],
        [0.8086, 0.2383, 0.5672, 0.3271, 0.7639]])

In [10]:
# The view method shows what the tensor y would look like when reshaped to be a 1x10, doesnt actually modify the tensor y. You would need to instantiate a variable with this value to do so.
y.view([1,10])

tensor([[0.7942, 0.4554, 0.8751, 0.8412, 0.3013, 0.8086, 0.2383, 0.5672, 0.3271,
         0.7639]])

In [11]:
# Shows that calling the view method on the y tensorflow didn't reshape the original tensorflow object y.
y

tensor([[0.7942, 0.4554, 0.8751, 0.8412, 0.3013],
        [0.8086, 0.2383, 0.5672, 0.3271, 0.7639]])